### ISSUE TITLE
Which color spaces are useful for histogram matching?

### ISSUE THREAD

**Issue by perrygeo** [mapbox/rio-hist#3]
Currently I'm using skimage for all but the LCH colorspace (which is implemented directly in rio-color)

Related to https://github.com/mapbox/rio-color/issues/28, we might want to make rio-color a more full-fledged colorspace module.

Let's identify which color spaces are useful for the purposes of histogram matching to guide that decision.

/cc @celoyd @virginiayung

**Comment by perrygeo** [comment]
## HSV
![srcref_hsv_plot](https://cloud.githubusercontent.com/assets/1151287/15253015/6411b6d4-18fe-11e6-81d3-1b3a2a85f436.jpg)

## LAB
![srcref_lab_plot](https://cloud.githubusercontent.com/assets/1151287/15253013/6410cf9e-18fe-11e6-8810-a4f89f200cae.jpg)

## LCH
*some issue with matching Hue as it's an angular measurement*
![srcref_lch_plot](https://cloud.githubusercontent.com/assets/1151287/15253014/641127fa-18fe-11e6-91c1-0ccade3aa4e9.jpg)

## LUV
![srcref_luv_plot](https://cloud.githubusercontent.com/assets/1151287/15253017/64122114-18fe-11e6-8b0f-4565ae74334c.jpg)

## RGB
![srcref_rgb_plot](https://cloud.githubusercontent.com/assets/1151287/15253016/6412083c-18fe-11e6-9a05-00a84b158127.jpg)

# XYZ
![srcref_xyz_plot](https://cloud.githubusercontent.com/assets/1151287/15253018/641330f4-18fe-11e6-8a13-4d687ae32138.jpg)

**Comment by virginiayung** [comment]
I've ran rio-hist on 21 adjacent scenes so that we can look at how histogram matching works under each color space at a slightly larger scale: 

### Source (NAIP 2013 CO & 2011 UT):

![all_tiny_naip](https://cloud.githubusercontent.com/assets/4450007/15368609/87c8a19e-1ce3-11e6-866b-a7a737f2a0f5.png)

### Reference (2 Landsat 8 Scenetifs):

![tiny_landsat](https://cloud.githubusercontent.com/assets/4450007/15372791/0b77edfc-1cf7-11e6-977e-47462c0de5d4.png)


### Cut Landsat 8 tiles:
![l_all](https://cloud.githubusercontent.com/assets/4450007/15368659/d925d4c6-1ce3-11e6-97c3-1315cfc27813.png)

### RGB:
![all_m_rgb](https://cloud.githubusercontent.com/assets/4450007/15369084/f6c7b6d2-1ce5-11e6-8a17-cbd1963a37ac.png)

### HSV:
![all_m_hsv](https://cloud.githubusercontent.com/assets/4450007/15369144/364eb378-1ce6-11e6-8c4f-964107528bf2.png)

### LUV:
![all_m_luv](https://cloud.githubusercontent.com/assets/4450007/15369211/859deb06-1ce6-11e6-94c2-dbac3aa01f68.png)


### LAB:
![all_m_lab](https://cloud.githubusercontent.com/assets/4450007/15369174/5658d3b0-1ce6-11e6-9eed-d72833092c09.png)

### LCH:
![all_m_lch](https://cloud.githubusercontent.com/assets/4450007/15369187/6852ead8-1ce6-11e6-87cf-d6576cd21162.png)

### XYZ:

![all_m_xyz](https://cloud.githubusercontent.com/assets/4450007/15369220/8cbb5680-1ce6-11e6-81eb-ec0a71d05a59.png)

======
## Notes:
1. **Clouds/Snow**: I included ~10% of clouds in the landsat 8 tiles which I used as reference. It seems that HSV was able to handle clouds in tiles 1X2 and 1X3 (first row, second and third tiles from the left) better than any other color spaces. RGB and XYZ are the two color spaces that took in most of near-255 pixel values. Below is the histogram for tile 1X2 in RGB:
    <img width="720" alt="screen shot 2016-05-18 at 12 07 25 pm" src="https://cloud.githubusercontent.com/assets/4450007/15371631/4937302c-1cf1-11e6-9ec9-7c5f19c93c8b.png">


2. **LCH produces blue/purple artifacts**: It seems to appear in high-contrast scenes. In this case, it is most apparent in tile 3x7, which covers the mountain ranges right outside of Dove Creek, CO . Here's a zoomed in view of this area:

    <img width="663" alt="screen shot 2016-05-18 at 12 46 18 pm" src="https://cloud.githubusercontent.com/assets/4450007/15372706/967ed614-1cf6-11e6-835e-f3450a25825c.png">


3. **Very subtle difference between LUV and LAB**: I had to toggle between to the outputs to really notice the difference between the two. I did notice that LUV took in more red and contrast for tiles 3X5 and 3X6. These original NAIP scene tifs for these two tiles contain a lot of contrast since they include mountain ranges and equivalent Landsat 8 scene tifs contain a bit of red and dark green.

4. **Handling redness**: HSV seems to pull in the redness more evenly than other color spaces. 

    ![red](https://cloud.githubusercontent.com/assets/4450007/15372644/48e74878-1cf6-11e6-94fd-3e5752f4cbe4.gif)

Would love to get your 👀 on this @celoyd @perrygeo. Any other interesting observation?

**Comment by celoyd** [comment]
Innnteresting. My impressions:

- Overall, no big positive or negative quality outliers in this test, besides full LCH’s H-skew. All of the others are basically shippable quality – no disqualifications in this round. The variations are small enough that picking favorites is impossible from a single sample.

- Hue artifacts in full LCH are to be expected, for the reason @perrygeo pointed out – H is angular, but this method treats it as an interval. I’m comfortable assuming that that’s where the blue is coming from.

I’d say we’ve seen, as much as possible from one test, that a 10th-ish percentile case (state boundary and some clouds) is fine across most of the colorspaces we’re looking at. That’s good to know.

To me it looks like the next action is to think about the 1st-ish percentile – somewhere that summoned the Blood River last time. Does that seem wise?

**Comment by virginiayung** [comment]
@celoyd: Here's a 100% crop of the tile 1X2 and 1X3:

#### NAIP:
![tiny_snow_full_naip](https://cloud.githubusercontent.com/assets/4450007/15405634/8e9ca36a-1db7-11e6-88a5-0b58365b0101.png)

#### Landsat 8:

![snow_3857](https://cloud.githubusercontent.com/assets/4450007/15405682/c1d73f42-1db7-11e6-9649-8392dee0aac0.png)

**Comment by virginiayung** [comment]
I found blood river 👻 in a different NAIP scene while histogram matching with Landsat 8 this time around. This is a different NAIP scene as the one found during the [last naip render](https://github.com/mapbox/satellite/issues/978#issuecomment-134780367), which is what got processed to our [basemap](https://hey.mapbox.com/satellite/data-inspector/?map=mapbox.satellite#13.52/34.4944/-114.3714). I've ran rio-hist on a couple more adjacent tiles and here are the results for these 12 NAIP scenes: 

##### Source: *Lake Havasu City, CA and AZ NAIP*

![tiny_all_down_naip](https://cloud.githubusercontent.com/assets/4450007/15406771/acf318e4-1dbc-11e6-8b00-157486c276bf.png)



##### Landsat 8:
![tiny_all_l](https://cloud.githubusercontent.com/assets/4450007/15406763/a0cba446-1dbc-11e6-9821-47360513d31a.png)



#### RGB:
![tiny_all_m_rgb](https://cloud.githubusercontent.com/assets/4450007/15406836/ef0acd4e-1dbc-11e6-8c51-c0a687d52275.png)


#### HSV:
![tiny_all_m_hsv](https://cloud.githubusercontent.com/assets/4450007/15406837/f129d552-1dbc-11e6-8633-bd9b5e6a6db6.png)
#### LUV:
![tiny_all_m_luv](https://cloud.githubusercontent.com/assets/4450007/15406846/fe4acd4a-1dbc-11e6-8a86-d6d6c4f769df.png)

#### LAB:
![tiny_all_m_lab](https://cloud.githubusercontent.com/assets/4450007/15406848/02b6c960-1dbd-11e6-8cfc-27c96191ed77.png)

#### LCH:
![tiny_all_m_lch](https://cloud.githubusercontent.com/assets/4450007/15406853/072becb4-1dbd-11e6-8a31-fed9822570c2.png)

#### XYZ:
![tiny_all_m_xyz](https://cloud.githubusercontent.com/assets/4450007/15406857/0a2a3c22-1dbd-11e6-8554-0acad784094c.png)

======

### Notes:
Found blood river where the redness of the land bled into Lake Havasu. Check out the bottom corner (tiles **3x3** and **3x4**). LUV showed the least sign of redness bleeding into the the water. HSV was a disaster. Here's what their histograms looks like (RGB, LUV, HSV):
![screen shot 2016-05-19 at 2 07 31 pm](https://cloud.githubusercontent.com/assets/4450007/15409768/17c57316-1dcb-11e6-99ff-92df6c4d04c0.png)






### Next: 

I'm checking on one other blood river candidate, so that we can 👀  and compare blood river scenes that resulted from using Landsat 5, 7 as reference source versus those from Landsat 8. This is what Panama City NAIP looks like now on our [basemap](http://a.tiles.mapbox.com/v3/brunosan.map-cyglrrfu/page.html#15/30.3644/-86.9466): 
<img width="1091" alt="screen shot 2015-08-26 at 6 09 31 pm" src="https://cloud.githubusercontent.com/assets/4450007/9510181/a7fa7470-4c1d-11e5-9c27-3d08ad405bff.png">

**Comment by perrygeo** [comment]
@virginiayung interesting!

HSV, with Hue being an discontinuous angular measurement just as in LCH, is probably a no-go. I think we can probably just **drop the idea of using HSV or LCH**, at least until we have a project with very specific matching requirements (like "match just the lightness of the reference data but retain the hue")

LUV looks promising and it's the only one that isn't yet directly supported by rio color - I'll work on that tomorrow. 

I'm concerned that part of the blood river effect might just be partially due to **too much red in the reference Landsat images**? Maybe it's just my eye but they seem way more red than similar imagery of the same area. How are we processing the landsat 8 data to get it to this point?

I'd also like to test on some different landscapes to see what the color balance looks like - the desert makes it hard to tell for sure since red rocks are not uncommon. But reddish coastal forests, not so much.

**Comment by virginiayung** [comment]
#### Source: 12 Pensacola, FL NAIP Scenes
![tiny_all_down_naip](https://cloud.githubusercontent.com/assets/4450007/15414266/e3c5818c-1ded-11e6-8f14-c084b1427114.png)

#### Reference: Pansharpened Landsat 8
![tiny_all_l](https://cloud.githubusercontent.com/assets/4450007/15414279/07fdc4ce-1dee-11e6-9f27-e531d2827c54.png)

======

#### RGB:
![tiny_all_rgb](https://cloud.githubusercontent.com/assets/4450007/15414327/7a9b814c-1dee-11e6-9af5-4b56f8bc0dc3.png)

======
#### HSV:
![tiny_all_hsv](https://cloud.githubusercontent.com/assets/4450007/15414330/7fd9e5b8-1dee-11e6-93ec-63970b15b00f.png)

======
#### LUV:
![tiny_all_luv](https://cloud.githubusercontent.com/assets/4450007/15414333/849c009a-1dee-11e6-8886-c573b1780192.png)

======
#### LAB:
![tiny_all_lab](https://cloud.githubusercontent.com/assets/4450007/15414336/88dcf86c-1dee-11e6-9b12-68b7435ee922.png)

======
#### LCH:
![tiny_all_lch](https://cloud.githubusercontent.com/assets/4450007/15414339/8d2d19ec-1dee-11e6-9339-7d3003d38cf7.png)

======
#### XYZ:
![tiny_all_xyz](https://cloud.githubusercontent.com/assets/4450007/15414341/8f525f2a-1dee-11e6-905d-153eb95c4ed8.png)

### Notes:
In this test suite, there were a lot of artifacts along the shore in these original NAIP scenes. Pansharpened Landsat 8 not only had better color, but also contained less artifacts. RGB and XYZ both did a pretty job suppressing these artifacts from NAIP. However, RGB created new blue ribbons in the deeper water as seen in the lower right tiles. @perrygeo I believe this is similar to blood river observed ^ but in reverse (bleeding from original NAIP). In any case, this is most likely due to the fact that these scenes contain more than one distinct features (land + water) and histogram matching has no knowledge of these distinct features, but treats the entire scene uniformly.

**Comment by perrygeo** [comment]
I think the answer to this question is going to be dependent on the needs of the project. Closing for now.

**Comment by Borda** [comment]
I have a use-case from medical - multi-stain histology tissue
![hist-matching](https://user-images.githubusercontent.com/6035284/56848167-052b4780-68e6-11e9-91ff-442edc5e6e76.png)
